name: Deploy
on:
  # Building on manual dispatch, and pushes to dev / main. But restricting
  workflow_dispatch:
  push:
    branches:
      - ourdna-browser-dev
      - milo-test

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ourdna-dev    # Add your cluster name here.
  GKE_ZONE: australia-southeast1-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: ourdna-browser-dev-green # Add your deployment name here.
  IMAGE: gnomad
  DOCKER_REGISTRY: australia-southeast1-docker.pkg.dev


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - uses: actions/checkout@v4

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/891247401758/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deploy@ourdna-browser-dev.iam.gserviceaccount.com"

      - id: "google-cloud-sdk-setup"
        name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "gcloud docker auth"
        run: |
          gcloud --quiet auth configure-docker australia-southeast1-docker.pkg.dev

      - name: "build api image"
        run: |
          docker build --provenance=false --file="deploy/dockerfiles/browser/api.dockerfile" \
            --tag "australia-southeast1-docker.pkg.dev/ourdna-browser-dev/gnomad/gnomad-api:$GITHUB_SHA \
            --tag "australia-southeast1-docker.pkg.dev/ourdna-browser-dev/gnomad/gnomad-api:latest \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$DOCKER_REGISTRY/$PROJECT_ID/gnomad/gnomad-api:$GITHUB_SHA"

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deploy
